export const US_STATES = [
  ["AL", "Alabama"], ["AK", "Alaska"], ["AZ", "Arizona"], ["AR", "Arkansas"],
  ["CA", "California"], ["CO", "Colorado"], ["CT", "Connecticut"], ["DE", "Delaware"],
  ["DC", "District of Columbia"], ["FL", "Florida"], ["GA", "Georgia"], ["HI", "Hawaii"],
  ["ID", "Idaho"], ["IL", "Illinois"], ["IN", "Indiana"], ["IA", "Iowa"],
  ["KS", "Kansas"], ["KY", "Kentucky"], ["LA", "Louisiana"], ["ME", "Maine"],
  ["MD", "Maryland"], ["MA", "Massachusetts"], ["MI", "Michigan"], ["MN", "Minnesota"],
  ["MS", "Mississippi"], ["MO", "Missouri"], ["MT", "Montana"], ["NE", "Nebraska"],
  ["NV", "Nevada"], ["NH", "New Hampshire"], ["NJ", "New Jersey"], ["NM", "New Mexico"],
  ["NY", "New York"], ["NC", "North Carolina"], ["ND", "North Dakota"], ["OH", "Ohio"],
  ["OK", "Oklahoma"], ["OR", "Oregon"], ["PA", "Pennsylvania"], ["RI", "Rhode Island"],
  ["SC", "South Carolina"], ["SD", "South Dakota"], ["TN", "Tennessee"], ["TX", "Texas"],
  ["UT", "Utah"], ["VT", "Vermont"], ["VA", "Virginia"], ["WA", "Washington"],
  ["WV", "West Virginia"], ["WI", "Wisconsin"], ["WY", "Wyoming"],
] as const;

export const US_CITIES: Record<string, readonly string[]> = {
  AL: ["Birmingham", "Huntsville", "Mobile", "Montgomery"], AK: ["Anchorage", "Fairbanks", "Juneau"],
  AZ: ["Chandler", "Mesa", "Phoenix", "Scottsdale", "Tucson"], AR: ["Fayetteville", "Fort Smith", "Little Rock"],
  CA: ["Fresno", "Los Angeles", "Oakland", "Sacramento", "San Diego", "San Francisco", "San Jose"],
  CO: ["Aurora", "Colorado Springs", "Denver", "Fort Collins"], CT: ["Bridgeport", "Hartford", "New Haven", "Stamford"],
  DE: ["Dover", "Newark", "Wilmington"], DC: ["Washington"], FL: ["Jacksonville", "Miami", "Orlando", "Tallahassee", "Tampa"],
  GA: ["Atlanta", "Augusta", "Columbus", "Savannah"], HI: ["Hilo", "Honolulu", "Kailua"],
  ID: ["Boise", "Idaho Falls", "Meridian"], IL: ["Aurora", "Chicago", "Rockford", "Springfield"],
  IN: ["Evansville", "Fort Wayne", "Indianapolis", "South Bend"], IA: ["Cedar Rapids", "Davenport", "Des Moines"],
  KS: ["Kansas City", "Overland Park", "Topeka", "Wichita"], KY: ["Bowling Green", "Lexington", "Louisville"],
  LA: ["Baton Rouge", "Lafayette", "New Orleans", "Shreveport"], ME: ["Augusta", "Bangor", "Portland"],
  MD: ["Annapolis", "Baltimore", "Frederick", "Rockville", "Silver Spring"], MA: ["Boston", "Cambridge", "Springfield", "Worcester"],
  MI: ["Ann Arbor", "Detroit", "Grand Rapids", "Lansing"], MN: ["Duluth", "Minneapolis", "Rochester", "Saint Paul"],
  MS: ["Biloxi", "Gulfport", "Jackson"], MO: ["Columbia", "Kansas City", "Springfield", "St. Louis"],
  MT: ["Billings", "Bozeman", "Helena", "Missoula"], NE: ["Lincoln", "Omaha"],
  NV: ["Carson City", "Henderson", "Las Vegas", "Reno"], NH: ["Concord", "Manchester", "Nashua"],
  NJ: ["Atlantic City", "Jersey City", "Newark", "Trenton"], NM: ["Albuquerque", "Las Cruces", "Santa Fe"],
  NY: ["Albany", "Buffalo", "New York", "Rochester", "Syracuse"], NC: ["Charlotte", "Durham", "Greensboro", "Raleigh"],
  ND: ["Bismarck", "Fargo", "Grand Forks"], OH: ["Cincinnati", "Cleveland", "Columbus", "Toledo"],
  OK: ["Norman", "Oklahoma City", "Tulsa"], OR: ["Eugene", "Portland", "Salem"],
  PA: ["Allentown", "Erie", "Harrisburg", "Philadelphia", "Pittsburgh"], RI: ["Cranston", "Newport", "Providence"],
  SC: ["Charleston", "Columbia", "Greenville"], SD: ["Aberdeen", "Pierre", "Rapid City", "Sioux Falls"],
  TN: ["Chattanooga", "Knoxville", "Memphis", "Nashville"], TX: ["Austin", "Dallas", "El Paso", "Fort Worth", "Houston", "San Antonio"],
  UT: ["Ogden", "Provo", "Salt Lake City"], VT: ["Burlington", "Montpelier", "Rutland"],
  VA: ["Alexandria", "Arlington", "Norfolk", "Richmond", "Virginia Beach"], WA: ["Bellevue", "Seattle", "Spokane", "Tacoma"],
  WV: ["Charleston", "Huntington", "Morgantown"], WI: ["Green Bay", "Madison", "Milwaukee"],
  WY: ["Casper", "Cheyenne", "Laramie"],
};
