import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { api } from "../../api/client";

const schema = z.object({ petId: z.string().uuid("Enter a valid pet record ID."), eventType: z.enum(["adoption", "return_from_adoption", "owner_surrender", "reclaim_by_owner", "transfer_in", "transfer_out", "foster_start", "foster_end"]), effectiveAt: z.string().min(1, "Enter the effective date and time."), sourceReference: z.string().trim().max(200).optional(), reasonCategory: z.string().trim().max(100).optional(), factualNote: z.string().trim().max(1000).optional() });
type Data = z.infer<typeof schema>;

export function CustodyEventForm({ lookupSessionId, onDone, onCancel }: { lookupSessionId: string; onDone: () => void; onCancel: () => void }) {
  const queryClient = useQueryClient();
  const mutation = useMutation({ mutationFn: (data: Data) => api.createCustodyEvent({ ...data, lookupSessionId }, crypto.randomUUID()), onSuccess: async (_event, data) => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["pet", data.petId] }), queryClient.invalidateQueries({ queryKey: ["pets"] })]); onDone(); } });
  const { register, handleSubmit, formState: { errors } } = useForm<Data>({ resolver: zodResolver(schema), defaultValues: { eventType: "adoption", effectiveAt: new Date().toISOString().slice(0, 16) } });
  return <form className="record-form" onSubmit={handleSubmit((data) => mutation.mutate(data))}><label htmlFor="event-pet-id">Pet record ID</label><input id="event-pet-id" {...register("petId")} placeholder="Select or paste this shelter’s pet UUID" />{errors.petId && <p className="form-error">{errors.petId.message}</p>}<div className="field-grid"><div><label htmlFor="event-type">Handoff type</label><select id="event-type" {...register("eventType")}><option value="adoption">Adoption</option><option value="return_from_adoption">Return from adoption</option><option value="owner_surrender">Owner surrender</option><option value="reclaim_by_owner">Reclaim by owner</option><option value="transfer_in">Transfer in</option><option value="transfer_out">Transfer out</option><option value="foster_start">Foster begins</option><option value="foster_end">Foster ends</option></select></div><div><label htmlFor="effective-at">Effective date and time</label><input id="effective-at" type="datetime-local" {...register("effectiveAt")} />{errors.effectiveAt && <p className="form-error">{errors.effectiveAt.message}</p>}</div></div><label htmlFor="source-reference">Source reference</label><input id="source-reference" {...register("sourceReference")} placeholder="Agreement or intake reference" /><label htmlFor="reason">Neutral reason category</label><input id="reason" {...register("reasonCategory")} placeholder="Use the approved shelter taxonomy" /><label htmlFor="event-note">Factual note</label><textarea id="event-note" rows={4} {...register("factualNote")} />{mutation.isError && <p className="form-error" role="alert">The handoff was not recorded. No duplicate was created; try again.</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onCancel}>Cancel</button><button className="button primary" disabled={mutation.isPending}>{mutation.isPending ? "Recording…" : "Record handoff"}</button></div></form>;
}
